POST fluttering-detail.railway.app:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==

{
    "statements": [
        {
            "statement": "MERGE (n:Person {name: $name, age: $age}) RETURN n",
            "parameters": {
                "name": "Alice",
                "age": 42
            }
        }
    ]

}